# Generated by Django 4.0.3 on 2022-03-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20220301_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
