# Generated by Django 4.0.3 on 2022-03-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_remove_customer_address_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='isbn'),
        ),
    ]
