# Generated by Django 3.1.3 on 2022-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20220326_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
