# Generated by Django 3.1.3 on 2022-03-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='bookstore.Order'),
        ),
        migrations.RemoveField(
            model_name='rentitem',
            name='order1',
        ),
        migrations.AddField(
            model_name='rentitem',
            name='order1',
            field=models.ManyToManyField(blank=True, null=True, to='bookstore.Order'),
        ),
    ]
