# Generated by Django 3.1.3 on 2022-03-27 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20220326_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.order'),
        ),
        migrations.RemoveField(
            model_name='rentitem',
            name='order1',
        ),
        migrations.AddField(
            model_name='rentitem',
            name='order1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.order'),
        ),
    ]
